name: Pull request or Push master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python3_tests:
    uses: ./.github/workflows/test-python-3.yml
