name: Pull request or Push master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python3_tests:
    uses: ./.github/workflows/test-python-3.yml
