name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        extras: ["", "numpy"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "poetry==2.2.1"
        poetry check --lock
        poetry install --with dev --extras "${{ matrix.extras }}"

    - name: Show python dependencies
      run: |
        python --version
        poetry run pip freeze

    - name: Run tests
      run: |
        poetry run pytest --capture=sys -vv tests
